from enum import Enum

class CaseStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    PENDING_REVIEW = "PENDING_REVIEW"
    DENIED = "DENIED"
    GAP_CLEARED = "GAP_CLEARED"
    GAP_ANALYSIS_RUNNING = "GAP_ANALYSIS_RUNNING"
    GAP_ANALYSIS_FAILED = "GAP_ANALYSIS_FAILED"
    ELIGIBILITY_CHECKING = "ELIGIBILITY_CHECKING"

class CasePriority(str, Enum):
    ROUTINE = "ROUTINE"
    URGENT = "URGENT"
    EMERGENT = "EMERGENT"

class PlaceOfService(str, Enum):
    INPATIENT = "INPATIENT"
    OUTPATIENT = "OUTPATIENT"
    OFFICE = "OFFICE"
