"""
Mock EHR (Electronic Health Record) data for seeding the cases table.
Each entry maps to the EHR model in models/ehr.py.
Updated with more realistic insurance companies, member IDs, and plans to support eligibility checks.
"""

import json
from constants.cases import CaseStatus, CasePriority, PlaceOfService

MOCK_EHR_CASES = [
    {
        "case_id":             "PA-20260215-0001",
        "status":              CaseStatus.SUBMITTED.value,
        "priority":            CasePriority.URGENT.value,
        "patient_id":          "PT-100234",
        "patient_name":        "John Doe",
        "date_of_birth":       "1985-06-12",
        "gender":              "Male",
        "insurance_company":   "Aetna",
        "member_id":           "W123456789",
        "group_number":        "GRP-5540",
        "plan_name":           "Aetna Choice POS II",
        "icd10_code":          "M17.11",
        "diagnosis":           "Primary osteoarthritis, right knee",
        "diagnosis_date":      "2026-01-20",
        "cpt_code":            "27447",
        "procedure_name":      "Total Knee Replacement",
        "procedure_date":      "2026-03-15",
        "place_of_service":    PlaceOfService.INPATIENT.value,
        "physician_name":      "Dr. Ramesh Kumar",
        "physician_npi":       "1234567890",
        "physician_specialty": "Orthopedic Surgery",
        "physician_phone":     "555-101-2020",
        "facility_name":       "City General Hospital",
        "lab_results":         json.dumps({
            "CBC":  {"WBC": "7.2", "RBC": "4.8", "Hemoglobin": "14.1"},
            "CMP":  {"Glucose": "95", "Creatinine": "0.9", "BUN": "15"},
            "PT/INR": {"PT": "12.5", "INR": "1.0"},
        }),
        "audit_log":           json.dumps([
            {"timestamp": "2026-02-15T09:00:00Z", "action": "CREATED",   "user": "sai@example.com"},
            {"timestamp": "2026-02-15T09:30:00Z", "action": "SUBMITTED", "user": "sai@example.com"},
        ]),
        "assigned_to":         "sai@example.com",
    },
    {
        "case_id":             "PA-20260218-0002",
        "status":              CaseStatus.APPROVED.value,
        "priority":            CasePriority.ROUTINE.value,
        "patient_id":          "PT-100567",
        "patient_name":        "Jane Smith",
        "date_of_birth":       "1972-11-03",
        "gender":              "Female",
        "insurance_company":   "UnitedHealthcare",
        "member_id":           "991234567",
        "group_number":        "GRP-7721",
        "plan_name":           "UHC Gold Plus",
        "icd10_code":          "E11.65",
        "diagnosis":           "Type 2 diabetes mellitus with hyperglycemia",
        "diagnosis_date":      "2025-08-10",
        "cpt_code":            "95251",
        "procedure_name":      "Continuous Glucose Monitoring (CGM) System",
        "procedure_date":      "2026-03-01",
        "place_of_service":    PlaceOfService.OFFICE.value,
        "physician_name":      "Dr. Ramesh Kumar",
        "physician_npi":       "1234567890",
        "physician_specialty": "Endocrinology",
        "physician_phone":     "555-101-2020",
        "facility_name":       "Metro Diabetes Clinic",
        "lab_results":         json.dumps({
            "HbA1c":   {"value": "8.2", "unit": "%"},
            "Fasting Glucose": {"value": "180", "unit": "mg/dL"},
        }),
        "audit_log":           json.dumps([
            {"timestamp": "2026-02-18T11:00:00Z", "action": "CREATED",   "user": "sai@example.com"},
            {"timestamp": "2026-02-19T14:00:00Z", "action": "SUBMITTED", "user": "sai@example.com"},
            {"timestamp": "2026-02-22T10:00:00Z", "action": "APPROVED",  "user": "admin@example.com"},
        ]),
        "assigned_to":         "sai@example.com",
    },
    {
        "case_id":             "PA-20260220-0003",
        "status":              CaseStatus.PENDING_REVIEW.value,
        "priority":            CasePriority.EMERGENT.value,
        "patient_id":          "PT-100789",
        "patient_name":        "Alice Johnson",
        "date_of_birth":       "1960-03-25",
        "gender":              "Female",
        "insurance_company":   "Cigna",
        "member_id":           "100234567",
        "group_number":        "GRP-3310",
        "plan_name":           "Cigna Open Access Plus",
        "icd10_code":          "I25.10",
        "diagnosis":           "Atherosclerotic heart disease of native coronary artery",
        "diagnosis_date":      "2026-02-10",
        "cpt_code":            "33533",
        "procedure_name":      "Coronary Artery Bypass Graft (CABG) x3",
        "procedure_date":      "2026-03-05",
        "place_of_service":    PlaceOfService.INPATIENT.value,
        "physician_name":      "Dr. Ramesh Kumar",
        "physician_npi":       "1234567890",
        "physician_specialty": "Cardiothoracic Surgery",
        "physician_phone":     "555-101-2020",
        "facility_name":       "Heart Care Institute",
        "lab_results":         json.dumps({
            "Troponin":  {"value": "0.02", "unit": "ng/mL"},
            "BNP":       {"value": "450",  "unit": "pg/mL"},
            "Lipid Panel": {"Total Cholesterol": "280", "LDL": "190", "HDL": "38", "Triglycerides": "260"},
        }),
        "audit_log":           json.dumps([
            {"timestamp": "2026-02-20T08:00:00Z", "action": "CREATED",        "user": "sai@example.com"},
            {"timestamp": "2026-02-20T08:15:00Z", "action": "SUBMITTED",      "user": "sai@example.com"},
            {"timestamp": "2026-02-20T09:00:00Z", "action": "PENDING_REVIEW", "user": "admin@example.com"},
        ]),
        "assigned_to":         "sai@example.com",
    },
    {
        "case_id":             "PA-20260225-0004",
        "status":              CaseStatus.DRAFT.value,
        "priority":            CasePriority.ROUTINE.value,
        "patient_id":          "PT-100901",
        "patient_name":        "Bob Williams",
        "date_of_birth":       "1990-09-17",
        "gender":              "Male",
        "insurance_company":   "Blue Cross Blue Shield",
        "member_id":           "ABC123456789",
        "group_number":        "GRP-9980",
        "plan_name":           "BCBS PPO Standard",
        "icd10_code":          "M54.5",
        "diagnosis":           "Low back pain",
        "diagnosis_date":      "2026-02-01",
        "cpt_code":            "72148",
        "procedure_name":      "MRI Lumbar Spine without Contrast",
        "procedure_date":      "2026-03-10",
        "place_of_service":    PlaceOfService.OUTPATIENT.value,
        "physician_name":      "Dr. Ramesh Kumar",
        "physician_npi":       "1234567890",
        "physician_specialty": "Orthopedic Surgery",
        "physician_phone":     "555-101-2020",
        "facility_name":       "Advanced Imaging Center",
        "lab_results":         json.dumps({}),
        "audit_log":           json.dumps([
            {"timestamp": "2026-02-25T16:00:00Z", "action": "CREATED", "user": "sai@example.com"},
        ]),
        "assigned_to":         "sai@example.com",
    },
    {
        "case_id":             "PA-20260301-0005",
        "status":              CaseStatus.DENIED.value,
        "priority":            CasePriority.ROUTINE.value,
        "patient_id":          "PT-101050",
        "patient_name":        "Maria Garcia",
        "date_of_birth":       "1978-12-30",
        "gender":              "Female",
        "insurance_company":   "Humana",
        "member_id":           "H12345678",
        "group_number":        "GRP-4450",
        "plan_name":           "Humana Gold Plus",
        "icd10_code":          "G43.909",
        "diagnosis":           "Migraine, unspecified, not intractable",
        "diagnosis_date":      "2025-12-15",
        "cpt_code":            "64615",
        "procedure_name":      "Botox Injection for Chronic Migraine",
        "procedure_date":      "2026-03-20",
        "place_of_service":    PlaceOfService.OFFICE.value,
        "physician_name":      "Dr. Ramesh Kumar",
        "physician_npi":       "1234567890",
        "physician_specialty": "Neurology",
        "physician_phone":     "555-101-2020",
        "facility_name":       "Neuroscience Associates",
        "lab_results":         json.dumps({}),
        "audit_log":           json.dumps([
            {"timestamp": "2026-03-01T10:00:00Z", "action": "CREATED",   "user": "sai@example.com"},
            {"timestamp": "2026-03-01T10:30:00Z", "action": "SUBMITTED", "user": "sai@example.com"},
            {"timestamp": "2026-03-04T15:00:00Z", "action": "DENIED",    "user": "admin@example.com",
             "reason": "Insufficient documentation of failed preventive treatments"},
        ]),
        "assigned_to":         "sai@example.com",
    },
]
